// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserProtection.Domain.Entities;

#nullable disable

namespace UserProtection.Domain.Migrations
{
    [DbContext(typeof(UserProtectionContext))]
    partial class UserProtectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AntiPhishingPattern", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatternId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PatternHtml")
                        .HasColumnType("text");

                    b.Property<string>("PatternText")
                        .HasColumnType("text");

                    b.Property<string>("PatternType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("PatternId")
                        .HasName("PK__AntiPhis__0A631B52D5DCBC6A");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TenantId", "Status" }, "IX_APP_Tenant_Status");

                    b.ToTable("AntiPhishingPatterns", "security");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssessmentId"));

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("AssessmentId")
                        .HasName("PK__Assessme__3D2BF81E83989AD6");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CourseId", "Status" }, "IX_Assessments_Course_Status");

                    b.ToTable("Assessments", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int?>("OptionId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerId")
                        .HasName("PK__Assessme__D4825004494214D8");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "AttemptId" }, "IX_Answers_Attempt");

                    b.ToTable("AssessmentAnswers", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AttemptId")
                        .HasName("PK__Assessme__891A68E6FEA4BA34");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AssessmentId", "UserId" }, "IX_AA_Assessment_User");

                    b.ToTable("AssessmentAttempts", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("OptionId")
                        .HasName("PK__Assessme__92C7A1FFB1589996");

                    b.HasIndex(new[] { "QuestionId" }, "IX_AO_Question");

                    b.ToTable("AssessmentOptions", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("QuestionId")
                        .HasName("PK__Assessme__0DC06FAC52E5C7BC");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AssessmentId", "OrderIndex" }, "UX_AQ_Assessment_Order")
                        .IsUnique();

                    b.ToTable("AssessmentQuestions", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Assessme__449EE12596F2F8ED");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AssessmentId", "UserId" }, "IX_AS_Assessment_User");

                    b.ToTable("AssessmentSubmissions", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5486486073394F");

                    b.HasIndex(new[] { "TenantId", "CreatedAt" }, "IX_AuditLogs_Tenant");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_AuditLogs_User");

                    b.ToTable("AuditLogs", "core");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__C92D71A7944F8561");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TenantId", "Status" }, "IX_Courses_Tenant_Status");

                    b.ToTable("Courses", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.CourseModule", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("ModuleId")
                        .HasName("PK__CourseMo__2B7477A7CCED40F0");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CourseId", "OrderIndex" }, "UX_Modules_Course_Order")
                        .IsUnique();

                    b.ToTable("CourseModules", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.CourseReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReviewId")
                        .HasName("PK__CourseRe__74BC79CEAA9F3D11");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "UserId", "CourseId" }, "UX_Reviews_User_Course")
                        .IsUnique();

                    b.ToTable("CourseReviews", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F68771B975EF4BF");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "UserId", "CourseId" }, "UX_Enroll_User_Course")
                        .IsUnique();

                    b.ToTable("Enrollments", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("FeatureId");

                    b.ToTable("Features", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("FrontendReturnUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Completed");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A3889A83FA2");

                    b.HasIndex(new[] { "SubscriptionId", "PaymentDate" }, "IX_Payments_Subscription");

                    b.HasIndex(new[] { "TransactionId" }, "UX_Payments_TransactionId")
                        .IsUnique()
                        .HasFilter("([TransactionId] IS NOT NULL)");

                    b.ToTable("Payments", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PlanId")
                        .HasName("PK__Plans__755C22B7374DD1D6");

                    b.HasIndex(new[] { "Name" }, "IX_Plans_Name")
                        .IsUnique();

                    b.ToTable("Plans", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.PlanCourse", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("PlanCourses", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("PlanFeatures", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__Subscrip__9A2B249DF1996288");

                    b.HasIndex("PlanId");

                    b.HasIndex(new[] { "Status" }, "IX_Subscriptions_Status");

                    b.HasIndex(new[] { "TenantId" }, "IX_Subscriptions_Tenant")
                        .HasFilter("([TenantId] IS NOT NULL)");

                    b.HasIndex(new[] { "UserId" }, "IX_Subscriptions_User")
                        .HasFilter("([UserId] IS NOT NULL)");

                    b.ToTable("Subscriptions", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.SubscriptionKey", b =>
                {
                    b.Property<int>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KeyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("KeyId")
                        .HasName("PK_SubscriptionKeys");

                    b.HasIndex("KeyValue")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionKeys", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.SuspiciousLink", b =>
                {
                    b.Property<int>("SuspiciousId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SuspiciousId"));

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CheckResult")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<int?>("MatchedPatternId")
                        .HasColumnType("integer");

                    b.Property<string>("PageContent")
                        .HasColumnType("text");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("SuspiciousId")
                        .HasName("PK__Suspicio__4D9FB8445F9672B9");

                    b.HasIndex("MatchedPatternId");

                    b.HasIndex(new[] { "CheckResult" }, "IX_SuspiciousLinks_Result");

                    b.HasIndex(new[] { "TenantId", "DetectedAt" }, "IX_SuspiciousLinks_Tenant");

                    b.HasIndex(new[] { "UserId", "DetectedAt" }, "IX_SuspiciousLinks_User");

                    b.ToTable("SuspiciousLinks", "security");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("TenantId")
                        .HasName("PK__Tenants__2E9B47E1CC998FAA");

                    b.HasIndex(new[] { "Domain" }, "IX_Tenants_Domain")
                        .IsUnique()
                        .HasFilter("([Domain] IS NOT NULL)");

                    b.ToTable("Tenants", "core");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.TenantUserAccess", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccessId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccessId")
                        .HasName("PK__TenantUs__4130D05FEB7B0B7A");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex(new[] { "UserId" }, "IX_TUA_User");

                    b.HasIndex(new[] { "TenantId", "UserId", "SubscriptionId" }, "UX_TUA_Tenant_User_Sub")
                        .IsUnique()
                        .HasFilter("([Status]='Active')");

                    b.ToTable("TenantUserAccess", "billing");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.TrustedLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("LinkId")
                        .HasName("PK__TrustedL__2D1221354FF931FE");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Domain" }, "IX_TrustedLinks_Domain");

                    b.HasIndex(new[] { "TenantId", "Domain", "Url" }, "UX_TrustedLinks_Tenant_Domain_Url")
                        .IsUnique()
                        .HasFilter("([Status]='Active')");

                    b.ToTable("TrustedLinks", "security");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex(new[] { "TenantId" }, "IX_Users_TenantId");

                    b.ToTable("Users", "core");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.UserCourseProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProgressId")
                        .HasName("PK__UserCour__BAE29CA512BFB486");

                    b.HasIndex("CourseId");

                    b.HasIndex("ModuleId");

                    b.HasIndex(new[] { "UserId", "CourseId" }, "IX_Progress_User_Course");

                    b.ToTable("UserCourseProgress", "learning");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.UserDomainEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntryId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<bool?>("Safe")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("EntryId");

                    b.HasIndex("UserId", "Domain", "EntryType")
                        .IsUnique()
                        .HasDatabaseName("UX_UDE_User_Domain_Type");

                    b.ToTable("UserDomainEntries", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserProtection.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AntiPhishingPattern", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AntiPhishingPatterns")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_APP_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("AntiPhishingPatterns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_APP_User");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Course", "Course")
                        .WithMany("Assessments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Assess_Course");

                    b.HasOne("UserProtection.Domain.Entities.CourseModule", "Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Assess_Module");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("Assessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Assess_User");

                    b.Navigation("Course");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentAnswer", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.AssessmentAttempt", "Attempt")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("AttemptId")
                        .IsRequired()
                        .HasConstraintName("FK_Ans_Attempt");

                    b.HasOne("UserProtection.Domain.Entities.AssessmentOption", "Option")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Ans_Option");

                    b.HasOne("UserProtection.Domain.Entities.AssessmentQuestion", "Question")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Ans_Question");

                    b.Navigation("Attempt");

                    b.Navigation("Option");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentAttempt", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AA_Assessment");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AA_User");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentOption", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.AssessmentQuestion", "Question")
                        .WithMany("AssessmentOptions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_AO_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AQ_Assessment");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AQ_User");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentSubmission", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AS_Assessment");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AS_User");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_User");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Course", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Courses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Courses_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Courses_User");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.CourseModule", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Course", "Course")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Modules_Course");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("CourseModules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Modules_User");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.CourseReview", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Course", "Course")
                        .WithMany("CourseReviews")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Course");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("CourseReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_User");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Enroll_Course");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Enroll_User");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Payment", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.PlanCourse", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Course", "Course")
                        .WithMany("PlanCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserProtection.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanCourses")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserProtection.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Plan");

                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_Subscriptions_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Subscriptions_User");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.SubscriptionKey", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionKeys")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionKeys_Subscriptions");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.SuspiciousLink", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.AntiPhishingPattern", "MatchedPattern")
                        .WithMany("SuspiciousLinks")
                        .HasForeignKey("MatchedPatternId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SL_Pattern");

                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SuspiciousLinks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SL_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("SuspiciousLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SL_User");

                    b.Navigation("MatchedPattern");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.TenantUserAccess", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Subscription", "Subscription")
                        .WithMany("TenantUserAccesses")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_TUA_Sub");

                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantUserAccesses")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_TUA_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("TenantUserAccesses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TUA_User");

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.TrustedLink", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TrustedLinks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TL_Tenant");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("TrustedLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TL_User");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.User", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.UserCourseProgress", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.Course", "Course")
                        .WithMany("UserCourseProgresses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Course");

                    b.HasOne("UserProtection.Domain.Entities.CourseModule", "Module")
                        .WithMany("UserCourseProgresses")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Progress_Module");

                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("UserCourseProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Progress_User");

                    b.Navigation("Course");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.UserDomainEntry", b =>
                {
                    b.HasOne("UserProtection.Domain.Entities.User", "User")
                        .WithMany("UserDomainEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AntiPhishingPattern", b =>
                {
                    b.Navigation("SuspiciousLinks");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentAttempts");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("AssessmentSubmissions");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentAttempt", b =>
                {
                    b.Navigation("AssessmentAnswers");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentOption", b =>
                {
                    b.Navigation("AssessmentAnswers");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Navigation("AssessmentAnswers");

                    b.Navigation("AssessmentOptions");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Course", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CourseModules");

                    b.Navigation("CourseReviews");

                    b.Navigation("Enrollments");

                    b.Navigation("PlanCourses");

                    b.Navigation("UserCourseProgresses");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.CourseModule", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("UserCourseProgresses");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Feature", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanCourses");

                    b.Navigation("PlanFeatures");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SubscriptionKeys");

                    b.Navigation("TenantUserAccesses");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AntiPhishingPatterns");

                    b.Navigation("AuditLogs");

                    b.Navigation("Courses");

                    b.Navigation("Subscriptions");

                    b.Navigation("SuspiciousLinks");

                    b.Navigation("TenantUserAccesses");

                    b.Navigation("TrustedLinks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UserProtection.Domain.Entities.User", b =>
                {
                    b.Navigation("AntiPhishingPatterns");

                    b.Navigation("AssessmentAttempts");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("AssessmentSubmissions");

                    b.Navigation("Assessments");

                    b.Navigation("AuditLogs");

                    b.Navigation("CourseModules");

                    b.Navigation("CourseReviews");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("Subscriptions");

                    b.Navigation("SuspiciousLinks");

                    b.Navigation("TenantUserAccesses");

                    b.Navigation("TrustedLinks");

                    b.Navigation("UserCourseProgresses");

                    b.Navigation("UserDomainEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
